### ISSUE TITLE
[Semaphore Boilerplate] Issue 1: Start structure of Semaphore Boilerplate  

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-boilerplate#1]
References:
https://github.com/semaphore-protocol/boilerplate

**Comment by mimisavage** [comment]
Can I work on this, please?

**Comment by Tronixtek** [comment]
I'd love to work on this!

**Comment by Benjtalkshow** [comment]
Could I try solving this?

**Comment by akintewe** [comment]
Is it okay if I tackle this?

**Comment by NueloSE** [comment]
I’d like to work on this.

using the provide template supplied above i would create a README.md file in the root of this project and then cover all necessary aspect covered in the sample

ETA <= 24hrs

**Comment by petersdt** [comment]
Can I take this from here?

**Comment by AnoukRImola** [comment]
Hi Guys! I'm a Frontend Developer and part of the Dojo. I have experience with this type of implementation.

I would address the requirements of this issue by implementing a monorepo structure to facilitate the connection between the contracts and the Frontend :)
