### ISSUE TITLE
[Semaphore Boilerplate] Issue 2: Add the PR template and Readme files

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-boilerplate#2]
The Semaphore-Stellar boilerplate needs an updated README file to include a clear explanation of how to use the boilerplate. Additionally, a standardized pull request (PR) template, similar to the format used in other repositories, should be created to streamline the contribution process and ensure consistency across PRs.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by 0xdevcollins** [comment]
Can I jump on this task?

**Comment by NueloSE** [comment]
Am a frontend dev and an experienced technical writer. Can I take this from here?
previous merge technical doc:
- [bytebeast](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/pull/104)
- [starknet foundry](https://github.com/foundry-rs/starknet-foundry/pull/2619)
- [cairo book](https://github.com/cairo-book/cairo-book/pull/952)

May I try my hand at this?

**Comment by mimisavage** [comment]
Can I take this from here?

**Comment by Iwueseiter** [comment]
Can I take this from here?
I'm a frontend/smart contract developer and a technical writer.
Here are links to comprehensive docs I've written and have been merged Flex-NFT-Marketplace/Flex-Marketplace-Contract#107, https://github.com/cairo-book/cairo-book/pull/1019, https://github.com/horuslabsio/tokenbound-contract-docs/pull/12, https://github.com/sivicstudio/starkludo/pull/102, https://hackmd.io/@-__sK8xkRjuXHkFZQLyYXg/HkLcMImM1l.

**Comment by Naomi-Gift** [comment]
Can I contribute to this one?
@ Can I work on this ?
I am a web3 developer/ Technical writer
I have experience in a lot of open source contributions especially in making Documentation
Here are some of the merged docs I’ve written
Flex-NFT-Marketplace/Flex-Marketplace-Contract@fc28412
https://github.com/dragan2234/worldcoin-scroll-bridge/pull/29
i will update the readme file to include a clear explanation of how to use the  broilerplate

**Comment by wheval** [comment]
Hello @evgongora, I'd like to handle this task. This would be my first contribution.
I would ensure to create a standard PR template to make it easier for contributors.
I would also update the README.md file with the correct way to use the boilerplate.
This would be my first contribution. Thanks
ETA is 1 day.

**Comment by Benjtalkshow** [comment]
Mind if I take this issue?

**Comment by mexes20** [comment]
Can I be assigned to work on this? I have three years experience in Software development and have contributed to some projects on OD here.

ETA: 10 hours.

**Comment by akintewe** [comment]
Can I take this from here?

**Comment by Michaelkingsdev** [comment]
May I take care of this?

**Comment by od-hunter** [comment]
Hello can I be assigned this please? I am a blockchain developer and I'm also good at documentations. I'll provide an updated README file to include a clear explanation of how to use the boilerplate. I'll provide a standardized pull request (PR) template, similar to the format used in other repositories, to streamline the contribution process and ensure consistency across PRs.
Below are some of the documentations I've done that were merged:
https://github.com/dojoengine/book/pull/308,
https://github.com/keep-starknet-strange/joyboy/pull/143,
https://github.com/Scaffold-Stark/ss2-docs/pull/31,
https://github.com/horuslabsio/Starknet-Scaffold/pull/94,
https://github.com/Hyle-org/examples/pull/15.

Please I’m ready to work, assign me please.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by salazarsebas** [comment]
# My background
As a member of the Dojo Coding community, I have experience in web2 and traditional technologies, as for web3 I have only been working for a few months and I have managed to make a few contributions, however, it is not an impediment for me to do my best in this issue, I will dedicate the necessary effort to contribute to the OSS.

# How I plan on tackling this issue
To solve this issue, I will perform the following steps:

- Write concise and clear steps to explain the Semaphore-Stellar Boilerplate.
- Create the template for the pull request template.
- Consult the mainteiners about their opinion about the solution.
- Ask for indications on the changes to be made.
- Make changes if necessary.

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a technical writer, frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by petersdt** [comment]
Can I contribute to this one?

**Comment by martinvibes** [comment]
i'm a frontend developer and a blockchain dev 
i would really like to contribute to your project 
 kindly assign :)

**Comment by salazarsebas** [comment]
Thanks for the assignment, I will work on it. ⛩️
