### ISSUE TITLE
[Semaphore  Boilerplate] Issue 3: Create the Code of conduct template and Contributing files

### ISSUE THREAD

**Issue by evgongora** [ZencypherSolutions/semaphore-stellar-boilerplate#3]
Description:

To foster a welcoming and inclusive environment, the Semaphore Boilerplate project needs a Code of Conduct and a comprehensive Contributing file. These documents will ensure that contributors understand the expectations for participation and the processes for making contributions.

**Comment by 0xOlivanode** [comment]
I’d like to resolve this.
To organise the  smart contracts, I'll create a contracts folder with subfolders for each contract. then place the source files (lib.rs and test.rs) in a src directory within each subfolder, along with a Cargo.toml file for dependencies. Lastly i'll update the workspace in the root Cargo.toml. This keeps the project modular and Soroban-compliant.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by NueloSE** [comment]
Would love to tackle this!
Am a frontend dev and an experienced technical writer. 
previous merge technical doc:
- [bytebeast](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/pull/104)
- [starknet foundry](https://github.com/foundry-rs/starknet-foundry/pull/2619)
- [cairo book](https://github.com/cairo-book/cairo-book/pull/952)

**Comment by mimisavage** [comment]
Can I attempt this issue?

**Comment by Joe-joe25** [comment]
May I be assigned to this? I love to take it making it my first contribution to the community

**Comment by caxtonacollins** [comment]
i will love to be assigned this issue. please assign me

**Comment by Benjtalkshow** [comment]
Could I take a shot at this?

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor and i  would love to work on this , my ETA is >12 Hours and ill create a draft PR in 10 hours time. Thank you for this opportunity. :)

**Comment by Michaelkingsdev** [comment]
Can I attempt this issue?

**Comment by od-hunter** [comment]
Hello can I be assigned this please? I am a blockchain developer and I'm also good at documentations. Below are some of the documentations I've done that were merged:

https://github.com/dojoengine/book/pull/308,
https://github.com/keep-starknet-strange/joyboy/pull/143,
https://github.com/Scaffold-Stark/ss2-docs/pull/31,
https://github.com/horuslabsio/Starknet-Scaffold/pull/94,
https://github.com/Hyle-org/examples/pull/15.

Please I’m ready to work, assign me please.

**Comment by petersdt** [comment]
I’d like to resolve this.

**Comment by ryzen-xp** [comment]
May I try my hand at this?

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by martinvibes** [comment]
i'm a technical writer, frontend dev and a blockchain dev 
please kindly assign :)

**Comment by t0fudev** [comment]
Hello! My name is t0fudev and I'm currently a computer science student and also a web3 developer. I'm fully confident on working on this issue since I have experience on working this type of files and also I had contributed on last OD Hack to this incredible project. 
I'm eager to continue contributing to this amazing project.

Sincerely, t0fudev

ETA: 1 day

**Comment by emarc99** [comment]
I'd love to give this a go.
